### ISSUE TITLE
Failed to npm run dist

### ISSUE THREAD

**Issue by Ehmydev** [LLK/scratch-desktop#113]
### Expected Behavior

Build the .exe without errors

### Actual Behavior

When I run "npm run dist", the cmd act like that:

```
D:\Dev\scratch\scratch-desktop-develop>npm run dist

> scratch-desktop@3.9.0 dist D:\Dev\scratch\scratch-desktop-develop
> npm run build-gui && npm run fetch && npm run compile -p && node ./scripts/electron-builder-wrapper.js


> scratch-desktop@3.9.0 build-gui D:\Dev\scratch\scratch-desktop-develop
> node ./scripts/run-in-gui.js build


> scratch-gui@0.1.0 build D:\Dev\scratch\scratch-desktop-develop\node_modules\scratch-gui
> npm run clean && webpack --progress --colors --bail


> scratch-gui@0.1.0 clean D:\Dev\scratch\scratch-desktop-develop\node_modules\scratch-gui
> rimraf ./build && mkdirp build && rimraf ./dist && mkdirp dist

D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'postcss-simple-vars'
Require stack:
- D:\Dev\scratch\scratch-desktop-develop\node_modules\scratch-gui\webpack.config.js
- D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\utils\convert-argv.js
- D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\cli.js
- D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (D:\Dev\scratch\scratch-desktop-develop\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\Dev\scratch\scratch-desktop-develop\node_modules\scratch-gui\webpack.config.js:12:19)
    at Module._compile (D:\Dev\scratch\scratch-desktop-develop\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (D:\Dev\scratch\scratch-desktop-develop\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\utils\convert-argv.js:116:13)
    at requireConfig (D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\utils\convert-argv.js:118:6)
    at D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\utils\convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\utils\convert-argv.js:123:15)
    at D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack-cli\bin\cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Dev\scratch\scratch-desktop-develop\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Dev\\scratch\\scratch-desktop-develop\\node_modules\\scratch-gui\\webpack.config.js',
    'D:\\Dev\\scratch\\scratch-desktop-develop\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'D:\\Dev\\scratch\\scratch-desktop-develop\\node_modules\\webpack-cli\\bin\\cli.js',
    'D:\\Dev\\scratch\\scratch-desktop-develop\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
```

### Steps to Reproduce

Follow what the readme says

### Operating System and Browser

Windows 10 and Firefox

**Comment by apple502j** [comment]
Just to make sure, did you run `npm install`?

**Comment by Ehmydev** [comment]
Of course
