### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by chrisruk** [LLK/scratch-desktop#162]
### Expected Behavior

When running scratch-desktop using branch 3.15 it ran without module errors, however with 3.17.1 I get the following error

### Actual Behavior

```
DISPLAY=:0.0 npm start

> scratch-desktop@3.17.1 start
> mkdirp ./dist && electron-webpack dev --bail --display-error-details --env.minify=false --no-progress

Error: Cannot find module 'autoprefixer'
Require stack:
- /home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/webpack.makeConfig.js
- /home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/webpack.main.js
- /home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/main.js
- /home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/dev/WebpackDevServerManager.js
- /home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/dev/dev-runner.js
- /home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/webpack.makeConfig.js:11:22)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/webpack.main.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/webpack.makeConfig.js',
    '/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/webpack.main.js',
    '/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/main.js',
    '/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/dev/WebpackDevServerManager.js',
    '/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/dev/dev-runner.js',
    '/home/pi/Repositories/scratch-desktop/scratch-dist/scratch-desktop/node_modules/electron-webpack/out/cli.js'
  ]
}
```

### Steps to Reproduce

I used branch 3.17.1 rather than branch 3.15.0 to get the above error message.

I notice autoprefixer etc. have been removed from the package.json of scratch-desktop after version 3.15.0.

Any pointers would be much appreciated!

### Operating System and Browser

Linux

**Comment by kebhr** [comment]
Still haven't found a solution?
