### ISSUE TITLE
Can't build setup.exe for windows

### ISSUE THREAD

**Issue by Brian586** [LLK/scratch-desktop#212]
### ERR_ELECTRON_BUILDER_CANNOT_EXECUTE failedTask=build 

I am trying to build a setup file for distribution on windows platform but I keep getting an error related to **_electron-builder-binaries_**.

This is my build configuration in **_package.json_** file;

> "build": {
>     "appId": "com.scratch.app",
>     "productName": "Scratch",
>     "target": "NSIS",
>     "win": {
>       "icon": "./buildResources/ScratchDesktop.ico"
>     },
>     "nsis": {
>       "artifactName": "Scratch-1.0.0-Setup.exe",
>       "oneClick": false,
>       "perMachine": false,
>       "allowToChangeInstallationDirectory": false,
>       "runAfterFinish": true,
>       "deleteAppDataOnUninstall": false,
>       "differentialPackage": true
>     }
>   }
> 

### Actual Behavior

When I run `npm run dist`, everything works fine then this happens;

> node ./scripts/electron-builder-wrapper.js "--mode=dist"

> running electron-builder with arguments: --windows,appx:ia32 appx:x64
  • electron-builder  version=22.13.1 os=10.0.19043
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  file=C:\src\ReactApps\scratch-desktop\node_modules\electron-webpack\out\electron-builder.js
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=ia32 electron=8.2.5 appOutDir=dist\win-ia32-unpacked
⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z": proxyconnect tcp: 
dial tcp :0: connectex: The requested address is not valid in its context.
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:107
github.com/develar/app-builder/pkg/download.downloadFromGithub
        /Volumes/data/Documents/app-builder/pkg/download/tool.go:63
github.com/develar/app-builder/pkg/download.DownloadWinCodeSign
        /Volumes/data/Documents/app-builder/pkg/download/tool.go:58
github.com/develar/app-builder/pkg/rcedit.editResources
        /Volumes/data/Documents/app-builder/pkg/rcedit/rcedit.go:30
github.com/develar/app-builder/pkg/rcedit.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/rcedit/rcedit.go:25
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/proc.go:225
runtime.goexit
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_amd64.s:1371  
  • Above command failed, retrying 0 more times
  ⨯ C:\src\ReactApps\scratch-desktop\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: C:\src\ReactApps\Afriblox\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (C:\src\ReactApps\scratch-desktop\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:476:26)
    at ChildProcess.emit (node:events:369:20)
    at ChildProcess.cp.emit (C:\src\ReactApps\scratch-desktop\node_modules\builder-util\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
From previous event:
    at processImmediate (node:internal/timers:464:21)
From previous event:
    at WinPackager.signApp (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\winPackager.ts:376:27)
    at WinPackager.doSignAfterPack (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\platformPackager.ts:327:16)
    at WinPackager.doPack (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\platformPackager.ts:312:7)
    at WinPackager.pack (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (C:\src\ReactApps\scratch-desktop\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\src\ReactApps\scratch-desktop\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (C:\src\ReactApps\scratch-desktop\node_modules\builder-util\src\promise.ts:12:14)
C:\src\ReactApps\scratch-desktop\scripts\electron-builder-wrapper.js:87
        throw new Error(`Child process returned status code ${result.status}`);
        ^

> Error: Child process returned status code 1
    at runBuilder (C:\src\ReactApps\scratch-desktop\scripts\electron-builder-wrapper.js:87:15)
    at main (C:\src\ReactApps\scratch-desktop\scripts\electron-builder-wrapper.js:199:9)
    at Object.<anonymous> (C:\src\ReactApps\scratch-desktop\scripts\electron-builder-wrapper.js:203:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

### Steps to Reproduce

1. `git clone https://github.com/LLK/scratch-desktop`
2. Run `npm install` to install all dependecies
3. Run `npm run dist`

`npm run clean`, `npm run compile` and `npm run fetch` should work fine. The error pops up while running `npm run doBuild -- --mode=dist`.
I am new to building Javascript/Electron desktop apps, if there's any critical step I missed kindly point it out.

### System Details
I'm using Windows 10

**Comment by Brian586** [comment]
On the root folder of the project, run;

`npm config delete proxy`
`npm config delete https-proxy`
