### ISSUE TITLE
npm start with locally cloned scratch-gui/vm fails by cannot find module error

### ISSUE THREAD

**Issue by kebhr** [LLK/scratch-desktop#231]
### Expected Behavior

Launch scratch-desktop with locally cloned scratch-gui, scratch-vm by npm start

### Actual Behavior

`npm start` fails by the error `Error: Cannot find module 'scratch-blocks/package.json'`

<details>
<summary>Full error logs</summary>

```
❯ npm start

> scratch-desktop@3.29.1 start
> mkdirp ./dist && electron-webpack dev --bail --display-error-details --env.minify=false --no-progress

Targeting Electron v15.3.1
main: Discarding electron-webpack default rule for /\.js$/
main: Keeping electron-webpack default rule for /\.node$/
main: Keeping electron-webpack default rule for /\.(png|jpg|gif)$/
10% building 1/1 modules 0 active┏ Renderer -------------------

  Targeting Electron v15.3.1

┗ ----------------------------
┏ Renderer -------------------

  Error: Cannot find module 'scratch-blocks/package.json'
  Require stack:
  - /Users/owner/Dev/scratch3-tello/scratch-desktop/webpack.renderer.js
  - /Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/out/main.js
  - /Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/webpack.renderer.config.js
  - /Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/webpack-cli/bin/utils/convert-argv.js
  - /Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/webpack-dev-server/bin/webpack-dev-server.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.resolve (node:internal/modules/cjs/helpers:108:19)
      at getModulePath (/Users/owner/Dev/scratch3-tello/scratch-desktop/webpack.renderer.js:7:58)
      at module.exports (/Users/owner/Dev/scratch3-tello/scratch-desktop/webpack.renderer.js:24:37)
      at applyCustom (/Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/src/main.ts:257:16)
      at WebpackConfigurator.applyCustomModifications (/Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/src/main.ts:265:14)
      at WebpackConfigurator.configure (/Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/src/main.ts:246:54)
      at configure (/Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/src/main.ts:376:10)

┗ ----------------------------
Renderer WDS exited with code 1
Error: Renderer WDS exited with code 1
    at ChildProcess.<anonymous> (/Users/owner/Dev/scratch3-tello/scratch-desktop/node_modules/electron-webpack/src/dev/ChildProcessManager.ts:62:32)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
┏ Main -----------------------

  Hash: d8d5b757565204311987
  Version: webpack 4.43.0
  Time: 748ms
  Built at: 05/15/2022 5:25:21 PM
        Asset      Size  Chunks                   Chunk Names
      main.js  5.25 MiB    main  [emitted]        main
  main.js.map  31.7 KiB    main  [emitted] [dev]  main
  Entrypoint main = main.js main.js.map
  [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] 582 bytes {main} [built]
  [./node_modules/fs-extra/lib/index.js] 719 bytes {main} [built]
  [./package.json] 2.76 KiB {main} [built]
  [./src/common/log.js] 304 bytes {main} [built]
  [./src/main/FileFilters.js] 2.91 KiB {main} [built]
  [./src/main/MacOSMenu.js] 828 bytes {main} [built]
  [./src/main/ScratchDesktopTelemetry.js] 5.42 KiB {main} [built]
  [./src/main/argv.js] 767 bytes {main} [built]
  [./src/main/index.js] 17.4 KiB {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [electron-devtools-installer] external "electron-devtools-installer" 42 bytes {main} [built]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {main} [built]
  [path] external "path" 42 bytes {main} [built]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {main} [built]
      + 467 hidden modules

┗ ----------------------------
c^CAssertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 178.
sh: line 1: 62710 Abort trap: 6           electron-webpack dev --bail --display-error-details --env.minify=false --no-progress
```
</details>

### Steps to Reproduce

```bash
git clone https://github.com/LLK/scratch-desktop.git -b v3.29.1 --depth 1
git clone https://github.com/LLK/scratch-gui.git -b scratch-desktop-v3.9.0 --depth 1
git clone https://github.com/LLK/scratch-vm.git -b 0.2.0-prerelease.20220223123949 --depth 1

cd scratch-vm &&
npm install &&
npm link &&

cd ../scratch-gui &&
npm install chromedriver@87.0.1 && # necessary to do npm install on M1 Mac
npm install &&
npm link scratch-vm &&
npm link &&

cd ../scratch-desktop &&
npm install &&
# neccessary to prevent error of autoprefixer not found
npm install --save-dev autoprefixer@^9 &&
npm install --save-dev postcss-simple-vars@4.1.0 &&
npm install --save-dev postcss-import@12.0.1 &&
npm link scratch-gui

npm start
```

### System Details

- Mac Studio (2022) (M1 Max)
- macOS 12.3
- node v16.15.0
- npm v8.5.5

**Comment by kebhr** [comment]
scratch-desktop depends on the scratch-gui dependency library. linking scratch-gui with npm link causes an error because the scratch-gui dependency library is excluded from node_modules.

I solved the problem by not using npm link and using symbolic links instead.
```
cd scratch-desktop
cd node_modules
rm -rf scratch-gui
ln -s ../../scratch-gui scratch-gui
```
